<?php

declare(strict_types=1);

namespace SocketBridge\Console;

use Illuminate\Console\Command;
use SocketBridge\Commands\CommandConsumer;

final class ConsumeCommand extends Command
{
    protected $aliases = ['socket:consume'];

    protected $signature = 'socket-bridge:consume
        {--once : Process one batch and exit}
        {--stop-when-empty : Exit after an empty batch}
        {--sleep=1 : Seconds to wait after an empty batch}
        {--consumer= : Unique Redis consumer name (generated by default)}
        {--max-time= : Exit between operations after this many seconds; zero disables the limit}
        {--memory= : Exit between operations above this memory usage in MiB; zero disables the limit}
        {--max-messages=0 : Exit after processing this many commands; zero means unlimited}';

    protected $description = 'Consume durable Socket Bridge commands in Laravel';

    public function handle(CommandConsumer $consumer): int
    {
        $name = $this->option('consumer') ?: gethostname().'-'.getmypid().'-'.bin2hex(random_bytes(4));

        return (new WorkerLoop)->run($this, fn (callable $shouldStop): int => $consumer->runOnce((string) $name, $shouldStop), 'commands', (string) $name);
    }
}
